/* 
 * Copyright (C) 2014 Center of Excellence in Information Assurance
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.coeia.searching;

import edu.coeia.cases.CaseFacade;
import edu.coeia.items.Item;
import edu.coeia.main.CaseMainFrame;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.swing.JFrame;

/**
 *
 * @author wajdyessam
 */
public class CaseSearchPanel extends javax.swing.JPanel {

    private AdvancedSearchPanel  advancedSearchPanel;
    private ConnectedSearchPanel connectedSearchPanel;
    
    private final CaseMainFrame caseFrame ;
    private final CaseFacade caseFacade ;
    
    private List<SearchHistory> searchOptions = new ArrayList<SearchHistory>();
    
    /** Creates new form CaseSearchPanel */
    public CaseSearchPanel(final JFrame frame) {
        initComponents();
        
        this.caseFrame = (CaseMainFrame) frame;
        this.caseFacade =  this.caseFrame.getCaseFacade();
        
        // add tapped pane
        this.advancedSearchPanel = new AdvancedSearchPanel(this);
        this.connectedSearchPanel = new ConnectedSearchPanel(this);
        this.caseSearchTappedPane.add("Advanced Search", advancedSearchPanel);
        this.caseSearchTappedPane.add("Connected Search", connectedSearchPanel);
    }
    
    public CaseFacade getCaseFacade() { return this.caseFacade; }
    public JFrame getParentJFrame() { return this.caseFrame ; }
    
    public void setFocusInAdvancedSearchPanel () {
        this.advancedSearchPanel.setQueryTextFeildFocusable();
    }
    
    void addSearchOption(final SearchHistory option) {
        this.searchOptions.add(option);
        this.connectedSearchPanel.updateSavedSearchTable();
    }
    
    List<SearchHistory> getSearchOptions() {
        return Collections.unmodifiableList(this.searchOptions);
    }
    
    static class SearchHistory {
        public SearchHistory(final String query, final String time, final SearchScope scope, 
                final List<Item> docs) {
            
            this.query = query ;
            this.time = time;
            this.scope = scope;
            this.documents = new ArrayList<Item>();
            this.documents.addAll(Collections.unmodifiableList(docs));
        }
        
        String query;
        String time;
        SearchScope scope;
        
        List<Item> documents;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caseSearchTappedPane = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(caseSearchTappedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(caseSearchTappedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane caseSearchTappedPane;
    // End of variables declaration//GEN-END:variables
}
