package edu.coeia.cases;

import chrriis.dj.nativeswing.swtimpl.components.JFileDialog;
import chrriis.dj.nativeswing.swtimpl.components.JDirectoryDialog;

import edu.coeia.chat.MSNParser;
import edu.coeia.chat.SkypeParser;
import edu.coeia.chat.SkypeMessage;

import edu.coeia.util.FilesPath;
import edu.coeia.util.Tuple;
import edu.coeia.internet.FilesFilter;
import edu.coeia.util.Utilities;

import edu.coeia.detector.OutlookDetector;
import edu.coeia.detector.FirefoxDetector;
import edu.coeia.detector.RegistryDetector;
import edu.coeia.detector.UsersDetector;
import edu.coeia.detector.YahooDetector ;
import edu.coeia.main.SmartCardDialog;

import javax.swing.JPanel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.DefaultListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import java.util.List ;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import java.io.File;
import java.io.IOException;

import java.awt.CardLayout;
import java.awt.Frame;
import java.util.Date;

/*
 * IndexWizard.java
 *
 * @author wajdyessam
 * 
 * Created on Jul 13, 2010, 2:00:51 PM
 * 
 */

public class CaseWizardDialog extends javax.swing.JDialog {

    private DefaultListModel documentModel;
    private DefaultListModel msnModel, yahooModel, skypeModel;
    private DefaultListModel pstModel;
    private DefaultListModel ieModel, ffModel;

    private Case currentCase;
    private String PATH = FilesPath.CASES_PATH;

    private Frame parent;
    private boolean isFullVersion;

    private JFileChooser fileChooser;
    
    boolean indexTheCase = false;   // index the case after create it
    /*
     * Wizard CardLayout - Panels Names
     */
    private String[] cardsName = {"indexInfoPanel","CaseWizardA1","CaseWizardA2","CaseWizardA3"};
    private int currentIndex = 0;
    

    /** Creates new form IndexWizard */
    public CaseWizardDialog(java.awt.Frame parent, boolean modal, boolean isFullVersion) {
        super(parent, modal);
        initComponents();
        
        this.parent = parent;
        this.isFullVersion = isFullVersion;

        // show first card indexInfoPanel and disable back button and finish button
        showPanel(cardsName[0], indexWizardPanel);
        backButton.setEnabled(false);
        finishButton.setEnabled(false);
        
        setLocationRelativeTo(parent);

        // creating model for all lists
        documentModel = new DefaultListModel();
    

       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        indexWizardPanel = new javax.swing.JPanel();
        indexInfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        caseNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        caseLocationTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        investigatorTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        CaseWizardA1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        CaseWizardA2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        CaseWizardA3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        indexFooterPanel = new javax.swing.JPanel();
        finishButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        indexHeaderPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Digital Evidence Miner: Create Index Wizard");
        setResizable(false);

        indexWizardPanel.setMaximumSize(new java.awt.Dimension(608, 361));
        indexWizardPanel.setPreferredSize(new java.awt.Dimension(608, 361));
        indexWizardPanel.setLayout(new java.awt.CardLayout());

        indexInfoPanel.setMaximumSize(new java.awt.Dimension(608, 361));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Case Name:");

        caseNameTextField.setText(" ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Case Location:");

        caseLocationTextField.setEditable(false);
        caseLocationTextField.setText(" ");

        browseButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Investigator Name:");

        investigatorTextField.setText(" ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Description:");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        javax.swing.GroupLayout indexInfoPanelLayout = new javax.swing.GroupLayout(indexInfoPanel);
        indexInfoPanel.setLayout(indexInfoPanelLayout);
        indexInfoPanelLayout.setHorizontalGroup(
            indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caseNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, indexInfoPanelLayout.createSequentialGroup()
                        .addComponent(caseLocationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(browseButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                    .addComponent(investigatorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE))
                .addContainerGap())
        );
        indexInfoPanelLayout.setVerticalGroup(
            indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexInfoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(caseLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel3)
                    .addComponent(investigatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        indexWizardPanel.add(indexInfoPanel, "indexInfoPanel");
        indexInfoPanel.getAccessibleContext().setAccessibleName("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("1) What type of evidence (Data Source) you want to add:");

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setText("Local Drive");

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setText("Local Folder");

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton3.setText("Encase Image");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("2) Would you like to import online e-mail accounts:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Username");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Password");

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton4.setText("Gmail");

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton5.setText("Hotmail");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Provider");

        javax.swing.GroupLayout CaseWizardA1Layout = new javax.swing.GroupLayout(CaseWizardA1);
        CaseWizardA1.setLayout(CaseWizardA1Layout);
        CaseWizardA1Layout.setHorizontalGroup(
            CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaseWizardA1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(CaseWizardA1Layout.createSequentialGroup()
                        .addGroup(CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addGroup(CaseWizardA1Layout.createSequentialGroup()
                                .addGroup(CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(39, 39, 39)
                                .addGroup(CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jTextField2)))
                            .addComponent(jLabel10))
                        .addGap(61, 61, 61)
                        .addGroup(CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jTextField3))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        CaseWizardA1Layout.setVerticalGroup(
            CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaseWizardA1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addGroup(CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel13)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        indexWizardPanel.add(CaseWizardA1, "CaseWizardA1");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText(" Evidence (Data Source) should be indexed to be searchable and pefrom all functions.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Would you like to index the case:");

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton6.setText("Yes (Recommended)");

        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton7.setText("No");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Would you like to calculate MD5 Hashe Values for the case so you can perform \"Hash Analysis\".");

        jRadioButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton8.setText("Yes");

        jRadioButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton9.setText("No");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Options:");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("Export copy of hashes to DEM Hash Library.");

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setText("Detect and cluster duplicated files within case files.");

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setText("Detect and cluster duplicated files compared with DEM Hash Library");

        javax.swing.GroupLayout CaseWizardA2Layout = new javax.swing.GroupLayout(CaseWizardA2);
        CaseWizardA2.setLayout(CaseWizardA2Layout);
        CaseWizardA2Layout.setHorizontalGroup(
            CaseWizardA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaseWizardA2Layout.createSequentialGroup()
                .addGroup(CaseWizardA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1)
                    .addGroup(CaseWizardA2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CaseWizardA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton8))
                        .addGap(59, 59, 59)
                        .addGroup(CaseWizardA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton7)))
                    .addGroup(CaseWizardA2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(CaseWizardA2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(CaseWizardA2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CaseWizardA2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        CaseWizardA2Layout.setVerticalGroup(
            CaseWizardA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaseWizardA2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(CaseWizardA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton6))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(CaseWizardA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton8))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        indexWizardPanel.add(CaseWizardA2, "CaseWizardA2");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("*Indexing Options*");

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox4.setText("Index archieved folders (ZIP, RAR)");

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox5.setText("Index embedded files on MS Office and Attachments");

        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox6.setText("Cache Images to view on Multimedia Viewer");

        jCheckBox7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox7.setText("Exclude Windows System Files from Indexing (Warning: Only choose this when you know that no evidences could be found within System Files): ");

        jRadioButton10.setText("Folder 1");

        jRadioButton11.setText("Folder 2");

        javax.swing.GroupLayout CaseWizardA3Layout = new javax.swing.GroupLayout(CaseWizardA3);
        CaseWizardA3.setLayout(CaseWizardA3Layout);
        CaseWizardA3Layout.setHorizontalGroup(
            CaseWizardA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaseWizardA3Layout.createSequentialGroup()
                .addGroup(CaseWizardA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CaseWizardA3Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel18))
                    .addGroup(CaseWizardA3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(CaseWizardA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton10)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CaseWizardA3Layout.setVerticalGroup(
            CaseWizardA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaseWizardA3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel18)
                .addGap(43, 43, 43)
                .addComponent(jCheckBox4)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox5)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox6)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox7)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton10)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton11)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        indexWizardPanel.add(CaseWizardA3, "CaseWizardA3");

        indexFooterPanel.setMaximumSize(new java.awt.Dimension(608, 63));
        indexFooterPanel.setPreferredSize(new java.awt.Dimension(608, 63));

        finishButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        finishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/finish.png"))); // NOI18N
        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/next.png"))); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/cancel.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indexFooterPanelLayout = new javax.swing.GroupLayout(indexFooterPanel);
        indexFooterPanel.setLayout(indexFooterPanelLayout);
        indexFooterPanelLayout.setHorizontalGroup(
            indexFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexFooterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(113, 113, 113)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        indexFooterPanelLayout.setVerticalGroup(
            indexFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexFooterPanelLayout.createSequentialGroup()
                .addGroup(indexFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indexFooterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(indexFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(indexFooterPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cancelButton))
                    .addGroup(indexFooterPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(finishButton)))
                .addGap(309, 309, 309))
        );

        indexHeaderPanel.setBackground(new java.awt.Color(51, 51, 51));
        indexHeaderPanel.setMaximumSize(new java.awt.Dimension(628, 76));
        indexHeaderPanel.setPreferredSize(new java.awt.Dimension(628, 76));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/2 copy.jpg"))); // NOI18N
        jLabel5.setText(" ");

        javax.swing.GroupLayout indexHeaderPanelLayout = new javax.swing.GroupLayout(indexHeaderPanel);
        indexHeaderPanel.setLayout(indexHeaderPanelLayout);
        indexHeaderPanelLayout.setHorizontalGroup(
            indexHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        indexHeaderPanelLayout.setVerticalGroup(
            indexHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        jSeparator1.setMaximumSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(indexWizardPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                            .addComponent(indexFooterPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(indexHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(indexHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indexWizardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indexFooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkforCaseLocationPath() {
        String text = caseNameTextField.getText().trim();
        
        if (! CaseNameChecker.isInvalidText(text)) {
            caseLocationTextField.setText(PATH + "\\" + text);
        } else {
            String word = CaseNameChecker.removeInvalid(text);
            caseLocationTextField.setText(PATH + "\\" + word);
        }
    }    

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JDirectoryDialog directoryDialog = new JDirectoryDialog();
        directoryDialog.show(CaseWizardDialog.this);
        String path = directoryDialog.getSelectedDirectory();

        if (path != null) {
            PATH = path;

            if (caseNameTextField.getText().trim().isEmpty()) {
                caseLocationTextField.setText(path);
            } else {
                caseLocationTextField.setText(path + "\\" + caseNameTextField.getText().trim());
            }
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        switch (currentIndex) {
                case 0:
               // if ( checkIndexInfoPanel() )
                next();
                break;
                
                case 1:
               // if ( checkIndexFileSystemPanel() )
                next();
                break;
                case 2:
                nextLast();
                 break;
               
       }
    }//GEN-LAST:event_nextButtonActionPerformed
        
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        switch (currentIndex) {
            
            case 1:
                 backFirst();
                break;

            case 2:
                back();
                break;
           case 3:
                back();
                break;     
                

                
        }
    }//GEN-LAST:event_backButtonActionPerformed
   
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        currentCase = null;
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void openDialog(FilesFilter filter, DefaultListModel model, JList list) {
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(CaseWizardDialog.this);

        if (result == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            addToList(path, model, list);
        }
    }

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
       


    }//GEN-LAST:event_finishButtonActionPerformed

    public boolean checkDirectIndex() {
        return indexTheCase;
    }
    
    private boolean createCase (Case aCase) {
        try {
            setCurrentCase(aCase);
            CaseManager.CaseOperation.writeCase(aCase);
            
            return true;
        }
        catch (Exception e){
            
        }
        
        return false;
    }
            
    /*
     * Check The IndexPanelInfo Before Go to the Next Panel
     * Check caseName if empty or is its existed
     * @return true if the all information are correct
     */
    private boolean checkIndexInfoPanel() {
        String caseName = getCaseName(caseLocationTextField.getText().trim());

        if (caseName == null || caseName.isEmpty()) {
            showErrorMessage("You must choose a Case Name","Empty Index Name");
            return false;
        }
        
        if (CaseManager.caseExists(caseName)) {
            showErrorMessage("The Case Name is Already Taken, Choose Another Name","Case Name Exists");
            return false;
        }

        if (caseName.contains("-")) { // doesn't needed now, case name checker will remove this character!
            showErrorMessage("Case Name Should Not Contains Illegal Chatacters (-)", "Please Change Case Name And Remove Any Special Character");
            return false;
        }
        
        String investigator = investigatorTextField.getText().trim();
        if (investigator.isEmpty()) {
            showErrorMessage("Investigator name is empty","Please Write A Clear Investigator Name");
            return false;
        }
        
        return (true);
    }
    
 
    
    /**
     * Check if their is folder name in case location text field
     */
    private String getCaseName(String path) {
        File file = new File(path);
        String name = file.getName();

        if (name.equalsIgnoreCase("CASES")) {
            return null;
        }

        return name;
    }
    
    /**
     * Move Current Panel in Card Layout to the Next Panel
     */
    private void next() {
        currentIndex++;
        showPanel(cardsName[currentIndex], indexWizardPanel);
        backButton.setEnabled(true);
        nextButton.setEnabled(true);
    }
    
    /**
     * Move this Panel to the Next Last Panel In the Card Layout
     * Enable This Finish Button
     */
    private void nextLast() {
        currentIndex++;
        showPanel(cardsName[currentIndex], indexWizardPanel);
        backButton.setEnabled(true);
        nextButton.setEnabled(false);
        finishButton.setEnabled(true);
    }
       
    /**
     * Return to Previous Panel in The Card Layout
     */
    private void backFirst() {
        currentIndex--;
      
        
        showPanel(cardsName[currentIndex], indexWizardPanel);
        backButton.setEnabled(false);
        nextButton.setEnabled(true);
    }
    
    /**
     * Return to The First Panel in the Card Layout
     * Disable Finish Button
     */
    private void back() {
        currentIndex--;
     
        showPanel(cardsName[currentIndex], indexWizardPanel);
        backButton.setEnabled(true);
        nextButton.setEnabled(true);
        finishButton.setEnabled(false);
    }
    
    /**
     * Show The Selected Panel in The CardLayout
     * @param panelName
     * @param name 
     */
    private void showPanel(String panelName, JPanel name) {
        CardLayout card = (CardLayout) name.getLayout();
        card.show(name, panelName);
    }
    
    

    
    // TODO: General List Model Methods, Move it to Utilties

    private void AddFromModelToList(DefaultListModel model, ArrayList<String> list) {
        for (int i = 0; i < model.size(); i++) {
            list.add((String) model.getElementAt(i));
        }
    }
        
    private void addToList(String path, DefaultListModel model, JList list) {
        if ((path != null || !path.startsWith("null")) && !existsInModel(path, model)) {
            model.addElement(path);
            list.setModel(model);
        }
    }

    private boolean existsInModel(String path, DefaultListModel model) {
        return model.contains(path);
    }

    private void removeFromList(String path, DefaultListModel model, JList list) {
        if (path != null) {
            model.removeElement(path);
            list.setModel(model);
        }
    }

    private void showEmptyMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Object Not Found", JOptionPane.ERROR_MESSAGE);
    }

    private void showErrorMessage(String msg, String title) {
        JOptionPane.showMessageDialog(CaseWizardDialog.this, msg, title, JOptionPane.ERROR_MESSAGE);
    }
    
    
    // TODO: check why there is acces/mutu ?
    
    public Case getCurrentCase() {
        return currentCase;
    }

    public void setCurrentCase(Case in) {
        currentCase = in;
    }
        
    /*
     * Case Name Checker
     * Check the Validity of The Case That Created By The User
     */
    private static class CaseNameChecker {
        private static boolean isInvalidText(String text) {
            for (String word : illegalCharacters) {
                if (text.contains(word)) {
                    return true;
                }
            }

            for (String word : reservedNames) {
                if (text.equalsIgnoreCase(word)) {
                    return true;
                }
            }

            return false;
        }

        private static String removeInvalid(String text) {
            for (String s : reservedNames) {
                if (text.equalsIgnoreCase(s)) {
                    text = "";
                    return text;
                }
            }

            StringBuilder result = new StringBuilder("");

            for (int i = 0; i < text.length(); i++) {
                String ch = text.charAt(i) + "";
                if (!isInvalidText(ch)) {
                    result.append(ch);
                }
            }

            return result.toString();
        }
        
        /*
         * Illegal case strings and characters
         */
        private static final String[] illegalCharacters = {"<", ">", ":", "\"", "/", "\\", "|", "?", "*", "-"};
        private static final String[] reservedNames = {
            "CON", "PRN", "AUX", "NUL", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7",
            "COM8", "COM9", "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9"
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CaseWizardA1;
    private javax.swing.JPanel CaseWizardA2;
    private javax.swing.JPanel CaseWizardA3;
    private javax.swing.JButton backButton;
    private javax.swing.JButton browseButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField caseLocationTextField;
    private javax.swing.JTextField caseNameTextField;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton finishButton;
    private javax.swing.JPanel indexFooterPanel;
    private javax.swing.JPanel indexHeaderPanel;
    private javax.swing.JPanel indexInfoPanel;
    private javax.swing.JPanel indexWizardPanel;
    private javax.swing.JTextField investigatorTextField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
