/* 
 * Copyright (C) 2014 Center of Excellence in Information Assurance
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.coeia.onlinemail;

import edu.coeia.cases.Case;
import edu.coeia.constants.ApplicationConstants;
import edu.coeia.wizard.EmailConfiguration;
import edu.coeia.wizard.EmailConfiguration.ONLINE_EMAIL_AGENT;

import java.io.IOException;

import java.sql.SQLException;

import javax.mail.MessagingException;
import javax.mail.NoSuchProviderException;

import javax.swing.JButton;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author wajdyessam
 */
public class EmailDownloaderDialog extends javax.swing.JDialog {

    OnlineEmailDownloader onlineEmailDownloader;
    
    private Case aCase ;   
    private EmailConfiguration emailConfiguration;

    public EmailDownloaderDialog(java.awt.Frame parent, boolean modal,
            final Case aCase, final EmailConfiguration emailConfiguration) throws SQLException, NoSuchProviderException, MessagingException, IOException, Exception {
        super(parent, modal);
        
        initComponents();
        setLocationRelativeTo(parent);        
        
        this.DownloadProgressBar.setIndeterminate(true);
        this.aCase = aCase;
        this.emailConfiguration = emailConfiguration;
        
        this.onlineEmailDownloader = new OnlineEmailDownloader(this,
            this.aCase.getCaseLocation() + "\\" + ApplicationConstants.CASE_ONLINE_EMAIL_ATTACHMENTS_FOLDER,
            this.aCase.getCaseLocation() + "\\" + ApplicationConstants.CASE_EMAIL_DB_FOLDER,
            this.aCase.getCaseLocation() + "\\" + ApplicationConstants.CASE_ARCHIVE_FOLDER
            );
    }
    
    public void start() {
        // if hotmail
        if (this.emailConfiguration.getSource() == ONLINE_EMAIL_AGENT.HOTMAIL) {
            if (this.onlineEmailDownloader.ConnectPop3Hotmail(this.emailConfiguration.getUserName(), 
                    this.emailConfiguration.getPassword())) {
                this.onlineEmailDownloader.execute();
                this.setVisible(true);
            }
        }
        
        if (this.emailConfiguration.getSource() == ONLINE_EMAIL_AGENT.YAHOO) {
            if (this.onlineEmailDownloader.ConnectPop3Yahoo(this.emailConfiguration.getUserName(),
                    this.emailConfiguration.getPassword())) {
                this.onlineEmailDownloader.execute();
                this.setVisible(true);
            }
        }
        
       if (this.emailConfiguration.getSource() == ONLINE_EMAIL_AGENT.GMAIL) {
            if (this.onlineEmailDownloader.ConnectIMAP(this.emailConfiguration.getUserName(),
                    this.emailConfiguration.getPassword())) {
                this.onlineEmailDownloader.execute();
                this.setVisible(true);
            }
        }
    }
    
    public OnlineEmailDownloader getOnlineEmailDownloader() {
        return this.onlineEmailDownloader;
    }
    
    public JButton getCancelButton() {
        return this.cancelButton;
    }
    
    public JButton getPauseButton(){
        return this.pauseButton;
    }
    
    public Case getCase() {
        return this.aCase;
    }

    public JTextField getFrom() {
        return this.from;
    }

    public JTextField getBCC() {
        return this.bcc;
    }

    public JTextField getCC() {
        return this.cc;
    }

    public JTextField getSentDate() {
        return this.sdate;
    }

    public JTextArea getAttachments() {
        return this.attachments;
    }

    public JTextField getSubject() {
        return this.subject;
    }

    public JTextField getTo() {
        return this.to;
    }
    
    public JProgressBar getDownloadProgressBar(){
        return this.DownloadProgressBar;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progresLabelPanel = new javax.swing.JPanel();
        FromjLabel = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        TojLabel = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        SubjectjLabel = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        SentDatejLabel = new javax.swing.JLabel();
        sdate = new javax.swing.JTextField();
        CCjLabel = new javax.swing.JLabel();
        cc = new javax.swing.JTextField();
        BCCjLabel = new javax.swing.JLabel();
        bcc = new javax.swing.JTextField();
        AttachjLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attachments = new javax.swing.JTextArea();
        pregressLabel = new javax.swing.JLabel();
        DownloadProgressBar = new javax.swing.JProgressBar();
        controllPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("edu/coeia/onlinemail/Bundle"); // NOI18N
        setTitle(bundle.getString("EmailDownloaderDialog.title")); // NOI18N

        progresLabelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("EmailDownloaderDialog.progresLabelPanel.border.title"))); // NOI18N
        progresLabelPanel.setForeground(new java.awt.Color(0, 51, 255));
        progresLabelPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        progresLabelPanel.setLayout(new javax.swing.BoxLayout(progresLabelPanel, javax.swing.BoxLayout.PAGE_AXIS));

        FromjLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FromjLabel.setText(bundle.getString("EmailDownloaderDialog.FromjLabel.text")); // NOI18N
        progresLabelPanel.add(FromjLabel);

        from.setEditable(false);
        from.setPreferredSize(new java.awt.Dimension(20, 20));
        progresLabelPanel.add(from);

        TojLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TojLabel.setText(bundle.getString("EmailDownloaderDialog.TojLabel.text")); // NOI18N
        progresLabelPanel.add(TojLabel);

        to.setEditable(false);
        progresLabelPanel.add(to);

        SubjectjLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SubjectjLabel.setText(bundle.getString("EmailDownloaderDialog.SubjectjLabel.text")); // NOI18N
        progresLabelPanel.add(SubjectjLabel);

        subject.setEditable(false);
        progresLabelPanel.add(subject);

        SentDatejLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SentDatejLabel.setText(bundle.getString("EmailDownloaderDialog.SentDatejLabel.text")); // NOI18N
        progresLabelPanel.add(SentDatejLabel);

        sdate.setEditable(false);
        progresLabelPanel.add(sdate);

        CCjLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CCjLabel.setText(bundle.getString("EmailDownloaderDialog.CCjLabel.text")); // NOI18N
        progresLabelPanel.add(CCjLabel);

        cc.setEditable(false);
        progresLabelPanel.add(cc);

        BCCjLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BCCjLabel.setText(bundle.getString("EmailDownloaderDialog.BCCjLabel.text")); // NOI18N
        progresLabelPanel.add(BCCjLabel);

        bcc.setEditable(false);
        progresLabelPanel.add(bcc);

        AttachjLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AttachjLabel.setText(bundle.getString("EmailDownloaderDialog.AttachjLabel.text")); // NOI18N
        progresLabelPanel.add(AttachjLabel);

        attachments.setColumns(20);
        attachments.setEditable(false);
        attachments.setRows(5);
        jScrollPane1.setViewportView(attachments);

        progresLabelPanel.add(jScrollPane1);

        pregressLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pregressLabel.setText(bundle.getString("EmailDownloaderDialog.pregressLabel.text")); // NOI18N
        progresLabelPanel.add(pregressLabel);
        progresLabelPanel.add(DownloadProgressBar);

        getContentPane().add(progresLabelPanel, java.awt.BorderLayout.PAGE_START);

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/cancel.png"))); // NOI18N
        cancelButton.setText(bundle.getString("EmailDownloaderDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        controllPanel.add(cancelButton);

        pauseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/mail.png"))); // NOI18N
        pauseButton.setText(bundle.getString("EmailDownloaderDialog.pauseButton.text")); // NOI18N
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });
        controllPanel.add(pauseButton);
        pauseButton.getAccessibleContext().setAccessibleName(bundle.getString("EmailDownloaderDialog.pauseButton.AccessibleContext.accessibleName")); // NOI18N

        getContentPane().add(controllPanel, java.awt.BorderLayout.SOUTH);

        getAccessibleContext().setAccessibleName(bundle.getString("EmailDownloaderDialog.AccessibleContext.accessibleName")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    if (onlineEmailDownloader!= null) {
        onlineEmailDownloader.cancel(true);
        this.setVisible(false);
    }
}//GEN-LAST:event_cancelButtonActionPerformed

private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
    if (onlineEmailDownloader != null) {
        onlineEmailDownloader.pauseDownloading();
    }
}//GEN-LAST:event_pauseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AttachjLabel;
    private javax.swing.JLabel BCCjLabel;
    private javax.swing.JLabel CCjLabel;
    private javax.swing.JProgressBar DownloadProgressBar;
    private javax.swing.JLabel FromjLabel;
    private javax.swing.JLabel SentDatejLabel;
    private javax.swing.JLabel SubjectjLabel;
    private javax.swing.JLabel TojLabel;
    private javax.swing.JTextArea attachments;
    private javax.swing.JTextField bcc;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cc;
    private javax.swing.JPanel controllPanel;
    private javax.swing.JTextField from;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pauseButton;
    private javax.swing.JLabel pregressLabel;
    private javax.swing.JPanel progresLabelPanel;
    private javax.swing.JTextField sdate;
    private javax.swing.JTextField subject;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
