/* 
 * Copyright (C) 2014 Center of Excellence in Information Assurance
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.coeia.investigation;

import edu.coeia.cases.CaseFacade;
import edu.coeia.searching.InvestigateDialog;
import edu.coeia.tasks.ExtensionFrequencyTask;
import edu.coeia.util.ApplicationLogging;

import java.awt.BorderLayout;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import java.util.logging.Logger;

/**
 *
 * @author wajdyessam
 */
public class ExtensionFrequencyPanel extends javax.swing.JPanel {

    private CaseFacade caseFacade; 
    private InvestigateDialog parentDialog;
    private final static Logger logger = ApplicationLogging.getLogger();
    
    /** Creates new form ExtensionFrequencyPanel */
    public ExtensionFrequencyPanel(InvestigateDialog dialog) {
        initComponents();
        
        this.caseFacade = dialog.getCaseFacade();
        this.parentDialog = dialog;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indexVisualizationButtonPanel = new javax.swing.JPanel();
        indexVisulizingButton = new javax.swing.JButton();
        indexVisualizingPiePanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("edu/coeia/investigation/Bundle"); // NOI18N
        indexVisualizationButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("ExtensionFrequencyPanel.indexVisualizationButtonPanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        indexVisulizingButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        indexVisulizingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/chart_pie.png"))); // NOI18N
        indexVisulizingButton.setText(bundle.getString("ExtensionFrequencyPanel.indexVisulizingButton.text")); // NOI18N
        indexVisulizingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexVisulizingButtonActionPerformed(evt);
            }
        });
        indexVisualizationButtonPanel.add(indexVisulizingButton);

        add(indexVisualizationButtonPanel, java.awt.BorderLayout.NORTH);

        indexVisualizingPiePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("ExtensionFrequencyPanel.indexVisualizingPiePanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        indexVisualizingPiePanel.setLayout(new java.awt.BorderLayout());
        add(indexVisualizingPiePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void indexVisulizingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexVisulizingButtonActionPerformed
        this.generateVisualization();
    }//GEN-LAST:event_indexVisulizingButtonActionPerformed
    
    public void setIndexVisualizationPanel(JPanel panel) {
        indexVisualizingPiePanel.removeAll();
        indexVisualizingPiePanel.add(panel, BorderLayout.CENTER);
        indexVisualizingPiePanel.revalidate();
    }
    
    private void generateVisualization() {;
        if ( ! this.caseFacade.getCaseHistory().getIsCaseIndexed() ) {
            JOptionPane.showMessageDialog(this, "please do the indexing operation first before do any operation",
                    "Case is not indexed",JOptionPane.ERROR_MESSAGE );
            return ;
        }
        
        ExtensionFrequencyTask task = new ExtensionFrequencyTask(this.caseFacade, this);
        task.startTask();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel indexVisualizationButtonPanel;
    private javax.swing.JPanel indexVisualizingPiePanel;
    private javax.swing.JButton indexVisulizingButton;
    // End of variables declaration//GEN-END:variables
}
