package edu.coeia.wizard;

import edu.coeia.gutil.JListUtil;
import edu.coeia.gutil.JTableUtil;
import edu.coeia.util.FilesPath;
import edu.coeia.managers.ApplicationManager;
import edu.coeia.cases.Case;
import edu.coeia.cases.CaseFacade;
import edu.coeia.gutil.GuiUtil;
import edu.coeia.onlinemail.DownloadEmail;

import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.DefaultListModel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.JFrame;

import java.awt.Color;
import java.awt.Component;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.File;
import java.io.FileNotFoundException;

import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import java.util.ArrayList;

import chrriis.dj.nativeswing.swtimpl.components.JDirectoryDialog;

/*
 * IndexWizard.java
 *
 * @author wajdyessam
 * 
 * Created on Jul 13, 2010, 2:00:51 PM
 * 
 */

public class CaseWizardDialog extends javax.swing.JDialog{
 
    private String PATH = FilesPath.CASES_PATH;
    private final List<String> evidencePathLocations;
    private final DefaultListModel sourcesListModel;
    
    private boolean indexTheCase = false;   // index the case after create it
    private final JFrame parentFrame;
    
    /*
     * Wizard CardLayout - Panels Names
     */
    private String[] cardsName = {"indexInfoPanel", "CaseWizardA1", "CaseWizardA2", "CaseWizardA3"};
    private int currentIndex = 0;
    private CaseFacade caseFacade; 

    /** Creates new form IndexWizard */
    public CaseWizardDialog(JFrame parent, boolean modal, boolean isFullVersion) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
       
        this.parentFrame = parent;
        ProgramFilesRadioButton.setVisible(false);
        WindowsFilesRadioButton.setVisible(false);
        backButton.setEnabled(false);
        finishButton.setEnabled(false);
        
        evidencePathLocations = new ArrayList<String>();
        sourcesListModel = new DefaultListModel();
        
        // Set Password 
        JPasswordField password = new JPasswordField();
        password.setBorder( new LineBorder(Color.BLACK) );
        EmailTable.getColumnModel().getColumn(1).setCellRenderer(new PasswordCellRenderer());
        
        // show first card indexInfoPanel and disable back button and finish button
        GuiUtil.showPanel(cardsName[0], indexWizardPanel);
        
        // add listener for index name text feild
        caseNameTextField.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                checkforCaseLocationPath();
            }

            public void removeUpdate(DocumentEvent e) {
                checkforCaseLocationPath();
            }

            public void changedUpdate(DocumentEvent e) {
                checkforCaseLocationPath();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataSourceButtonGroup = new javax.swing.ButtonGroup();
        YesNoIndexButtonGroup = new javax.swing.ButtonGroup();
        YesNoMD5HashButtonGroup = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        indexWizardPanel = new javax.swing.JPanel();
        indexInfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        caseNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        caseLocationTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        investigatorTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        CaseWizardA1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        addDriverButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sourcesJList = new javax.swing.JList();
        removeButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        EmailTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CaseWizardA2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NoIndexRadioButton = new javax.swing.JRadioButton();
        DetectClusterCaseRadioButton = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        YesIndexRadioButton = new javax.swing.JRadioButton();
        DetectClusterLibraryRadioButton = new javax.swing.JCheckBox();
        NoMD5RadioButton = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        YesMD5RadioButton = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CaseWizardA3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        CacheImageCheckBox = new javax.swing.JCheckBox();
        ExcludeSystemFilesCheckBox = new javax.swing.JCheckBox();
        IndexZipCheckBox = new javax.swing.JCheckBox();
        WindowsFilesRadioButton = new javax.swing.JRadioButton();
        ProgramFilesRadioButton = new javax.swing.JRadioButton();
        IndexEmbeddedFilesCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        IndexChatCheckBox = new javax.swing.JCheckBox();
        DetectBrowserCheckBox = new javax.swing.JCheckBox();
        indexFooterPanel = new javax.swing.JPanel();
        finishButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Digital Evidence Miner: Create Index Wizard");
        setResizable(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/DEMMainLogo.jpg"))); // NOI18N

        indexWizardPanel.setMaximumSize(new java.awt.Dimension(608, 361));
        indexWizardPanel.setPreferredSize(new java.awt.Dimension(608, 361));
        indexWizardPanel.setLayout(new java.awt.CardLayout());

        indexInfoPanel.setMaximumSize(new java.awt.Dimension(608, 361));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Case Name:");

        caseNameTextField.setText(" ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Case Location:");

        caseLocationTextField.setEditable(false);
        caseLocationTextField.setText(" ");

        browseButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        browseButton.setText("Browse...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Investigator Name:");

        investigatorTextField.setText(" ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Description:");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setFont(new java.awt.Font("Courier New", 1, 18));
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        javax.swing.GroupLayout indexInfoPanelLayout = new javax.swing.GroupLayout(indexInfoPanel);
        indexInfoPanel.setLayout(indexInfoPanelLayout);
        indexInfoPanelLayout.setHorizontalGroup(
            indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexInfoPanelLayout.createSequentialGroup()
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indexInfoPanelLayout.createSequentialGroup()
                        .addComponent(caseLocationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(caseNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(investigatorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap())
        );
        indexInfoPanelLayout.setVerticalGroup(
            indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexInfoPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(caseLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(browseButton))
                .addGap(18, 18, 18)
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel3)
                    .addComponent(investigatorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(indexInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addContainerGap())
        );

        indexWizardPanel.add(indexInfoPanel, "indexInfoPanel");
        indexInfoPanel.getAccessibleContext().setAccessibleName("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("What type of evidence (Data Source) you want to add:"));

        addDriverButton.setText("Add Source");
        addDriverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDriverButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));

        sourcesJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sourcesJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                sourcesJListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(sourcesJList);

        removeButton.setText("Remove Source");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Unmount Encase Image");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDriverButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(addDriverButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Would you like to import online e-mail accounts:"));

        EmailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Provider"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(EmailTable);

        jButton2.setText("Remove Email");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Add Email");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout CaseWizardA1Layout = new javax.swing.GroupLayout(CaseWizardA1);
        CaseWizardA1.setLayout(CaseWizardA1Layout);
        CaseWizardA1Layout.setHorizontalGroup(
            CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CaseWizardA1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(569, 569, 569))
            .addGroup(CaseWizardA1Layout.createSequentialGroup()
                .addGroup(CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        CaseWizardA1Layout.setVerticalGroup(
            CaseWizardA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaseWizardA1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        indexWizardPanel.add(CaseWizardA1, "CaseWizardA1");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Additonal Options"));

        YesNoIndexButtonGroup.add(NoIndexRadioButton);
        NoIndexRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        NoIndexRadioButton.setText("No");

        DetectClusterCaseRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        DetectClusterCaseRadioButton.setSelected(true);
        DetectClusterCaseRadioButton.setText("Detect and cluster duplicated files within case files.");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel15.setText("Would you like to index the case after creating?");

        YesNoIndexButtonGroup.add(YesIndexRadioButton);
        YesIndexRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        YesIndexRadioButton.setSelected(true);
        YesIndexRadioButton.setText("Yes (Recommended)");

        DetectClusterLibraryRadioButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        DetectClusterLibraryRadioButton.setSelected(true);
        DetectClusterLibraryRadioButton.setText("Detect and cluster duplicated files compared with DEM Hash Library");
        DetectClusterLibraryRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetectClusterLibraryRadioButtonActionPerformed(evt);
            }
        });

        YesNoMD5HashButtonGroup.add(NoMD5RadioButton);
        NoMD5RadioButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        NoMD5RadioButton.setText("No");
        NoMD5RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoMD5RadioButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setText(" Evidence (Data Source) should be indexed to be searchable and pefrom all functions.");

        YesNoMD5HashButtonGroup.add(YesMD5RadioButton);
        YesMD5RadioButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        YesMD5RadioButton.setSelected(true);
        YesMD5RadioButton.setText("Yes");
        YesMD5RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesMD5RadioButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setText("Would you like to calculate MD5 Hashe Values for the case so you can do Hash Analysis ?");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel17.setText("Options:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(YesMD5RadioButton)
                        .addGap(157, 157, 157)
                        .addComponent(NoMD5RadioButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(YesIndexRadioButton)
                        .addGap(59, 59, 59)
                        .addComponent(NoIndexRadioButton))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(DetectClusterLibraryRadioButton)
                    .addComponent(jLabel17)
                    .addComponent(DetectClusterCaseRadioButton))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoIndexRadioButton)
                    .addComponent(YesIndexRadioButton))
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoMD5RadioButton)
                    .addComponent(YesMD5RadioButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DetectClusterCaseRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DetectClusterLibraryRadioButton)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout CaseWizardA2Layout = new javax.swing.GroupLayout(CaseWizardA2);
        CaseWizardA2.setLayout(CaseWizardA2Layout);
        CaseWizardA2Layout.setHorizontalGroup(
            CaseWizardA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CaseWizardA2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CaseWizardA2Layout.setVerticalGroup(
            CaseWizardA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaseWizardA2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        indexWizardPanel.add(CaseWizardA2, "CaseWizardA2");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Indexing Options"));

        CacheImageCheckBox.setFont(new java.awt.Font("Tahoma", 1, 11));
        CacheImageCheckBox.setSelected(true);
        CacheImageCheckBox.setText("Cache Images to view on Multimedia Viewer");

        ExcludeSystemFilesCheckBox.setFont(new java.awt.Font("Tahoma", 1, 11));
        ExcludeSystemFilesCheckBox.setText("Exclude Windows System Files from Indexing: ");
        ExcludeSystemFilesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcludeSystemFilesCheckBoxActionPerformed(evt);
            }
        });

        IndexZipCheckBox.setFont(new java.awt.Font("Tahoma", 1, 11));
        IndexZipCheckBox.setSelected(true);
        IndexZipCheckBox.setText("Index archieved folders (ZIP, RAR)");

        WindowsFilesRadioButton.setText("Windows Files");

        ProgramFilesRadioButton.setText("Program Files");

        IndexEmbeddedFilesCheckBox.setFont(new java.awt.Font("Tahoma", 1, 11));
        IndexEmbeddedFilesCheckBox.setSelected(true);
        IndexEmbeddedFilesCheckBox.setText("Index embedded files on MS Office and Attachments");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("(Warning: Only choose this when you know that no evidences could be found within System Files)");

        IndexChatCheckBox.setFont(new java.awt.Font("Tahoma", 1, 11));
        IndexChatCheckBox.setSelected(true);
        IndexChatCheckBox.setText("Index Chat Sessions ( MSN, YAHOO, and SKYPE)");

        DetectBrowserCheckBox.setFont(new java.awt.Font("Tahoma", 1, 11));
        DetectBrowserCheckBox.setSelected(true);
        DetectBrowserCheckBox.setText("Detect and read Browsers (FireFox, IE) Sessions");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IndexZipCheckBox)
                    .addComponent(IndexChatCheckBox)
                    .addComponent(IndexEmbeddedFilesCheckBox)
                    .addComponent(DetectBrowserCheckBox)
                    .addComponent(CacheImageCheckBox)
                    .addComponent(ExcludeSystemFilesCheckBox))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ProgramFilesRadioButton)
                    .addComponent(WindowsFilesRadioButton))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IndexZipCheckBox)
                .addGap(5, 5, 5)
                .addComponent(IndexChatCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IndexEmbeddedFilesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DetectBrowserCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CacheImageCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ExcludeSystemFilesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProgramFilesRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WindowsFilesRadioButton)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout CaseWizardA3Layout = new javax.swing.GroupLayout(CaseWizardA3);
        CaseWizardA3.setLayout(CaseWizardA3Layout);
        CaseWizardA3Layout.setHorizontalGroup(
            CaseWizardA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CaseWizardA3Layout.setVerticalGroup(
            CaseWizardA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CaseWizardA3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        indexWizardPanel.add(CaseWizardA3, "CaseWizardA3");

        indexFooterPanel.setMaximumSize(new java.awt.Dimension(608, 63));
        indexFooterPanel.setPreferredSize(new java.awt.Dimension(608, 63));

        finishButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        finishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/finish.png"))); // NOI18N
        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/next.png"))); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/coeia/main/resources/cancel.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout indexFooterPanelLayout = new javax.swing.GroupLayout(indexFooterPanel);
        indexFooterPanel.setLayout(indexFooterPanelLayout);
        indexFooterPanelLayout.setHorizontalGroup(
            indexFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexFooterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(71, 71, 71)
                .addComponent(cancelButton)
                .addGap(18, 18, 18)
                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        indexFooterPanelLayout.setVerticalGroup(
            indexFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexFooterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(indexFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indexFooterPanelLayout.createSequentialGroup()
                        .addGroup(indexFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(309, 309, 309))
                    .addGroup(indexFooterPanelLayout.createSequentialGroup()
                        .addGroup(indexFooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(finishButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jSeparator1.setMaximumSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(indexFooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                    .addComponent(indexWizardPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indexWizardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 2, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indexFooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkforCaseLocationPath() {
        String text = caseNameTextField.getText().trim();

        if (!CaseNameChecker.isInvalidText(text)) {
            caseLocationTextField.setText(PATH + "\\" + text);
        } else {
            String word = CaseNameChecker.removeInvalid(text);
            caseLocationTextField.setText(PATH + "\\" + word);
        }
    }

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        switch (currentIndex) {
            case 0:
                try {
                    if (checkWizardFirstPanel()) {
                        next();
                    }
                } catch (Exception ex) {
                    Logger.getLogger(CaseWizardDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            break;

            case 1:
                if (checkWizardSecondPanel()) {
                    next();
                }
            break;
                
            case 2:
                nextLast();
            break;

        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        switch (currentIndex) {
            case 1:
                backFirst();
            break;

            case 2:
                evidencePathLocations.clear();
                back();
            break;
                
            case 3:
                back();
            break;
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.caseFacade = null;
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void autoDetectIEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoDetectIEButtonActionPerformed
    }//GEN-LAST:event_autoDetectIEButtonActionPerformed

    private void autoDetectFFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoDetectFFButtonActionPerformed
    }//GEN-LAST:event_autoDetectFFButtonActionPerformed

    private void autoDetectMSNButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoDetectMSNButtonActionPerformed
    }//GEN-LAST:event_autoDetectMSNButtonActionPerformed

    private void autoDetectYahooButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoDetectYahooButtonActionPerformed
    }//GEN-LAST:event_autoDetectYahooButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        try {
            List<EmailConfiguration> emailInfos = new ArrayList<EmailConfiguration>();
            Object[][] data = getEmailTableData();
            for (int c = 0; c < EmailTable.getRowCount(); c++) {
                emailInfos.add(EmailConfiguration.
                        newInstance(String.valueOf(data[c][0]),
                                    String.valueOf(data[c][1]),
                                    EmailConfiguration.ONLINE_EMAIL_AGENT.valueOf(String.valueOf(data[c][2]))
                        ));
            }

            this.setVisible(false);

            // set direct indexing the case after creating
            this.indexTheCase = YesIndexRadioButton.isSelected() ;
           
            // Build Case
            Case currentCase = new Case.CaseBuilder(
                    caseNameTextField.getText().trim(),
                    caseLocationTextField.getText().trim(),
                    investigatorTextField.getText().trim(),
                    descriptionTextArea.getText().trim(),
                    evidencePathLocations, new Date(), 0)
                    .getCacheImages(CacheImageCheckBox.isSelected())
                    .detectDuplicationWithinCase(DetectClusterCaseRadioButton.isSelected())
                    .detectDuplicationWithHashLibrary(DetectClusterLibraryRadioButton.isSelected())
                    .execludeFileSystem(ExcludeSystemFilesCheckBox.isSelected())
                    .computeHashForEveryItem(YesMD5RadioButton.isSelected())
                    .doIndexingAfterCaseCreation(YesIndexRadioButton.isSelected())
                    .indexArchiveFiles(IndexZipCheckBox.isSelected())
                    .indexEmbeddedDocuments(IndexEmbeddedFilesCheckBox.isSelected())
                    .isIndexChatSessions(IndexChatCheckBox.isSelected())
                    .detectInternetBrowsers(DetectBrowserCheckBox.isSelected())
                    .addEmailConfiguration(emailInfos)
            .build();
            
            this.caseFacade = CaseFacade.newInstance(currentCase);
            if (!caseFacade.createCase()) {     
                showErrorMessage("Cannot Create New Case", "Error in Creating new Case");
                return;
            }

            // download emails
            for (EmailConfiguration s : emailInfos) {
                try {
                    DownloadEmail downloder = new DownloadEmail(currentCase, s);
                    downloder.download(this.parentFrame);
                } 
                catch (Exception ex) {
                    Logger.getLogger(CaseWizardDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } catch (IOException ex) {
            Logger.getLogger(CaseWizardDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_finishButtonActionPerformed

    public Object[][] getEmailTableData() {
        return JTableUtil.getTableData(EmailTable);
    }
    
private void ExcludeSystemFilesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcludeSystemFilesCheckBoxActionPerformed
    if (!ProgramFilesRadioButton.isVisible() && !WindowsFilesRadioButton.isVisible()) {
        ProgramFilesRadioButton.setVisible(true);
        WindowsFilesRadioButton.setVisible(true);
    } else {
        ProgramFilesRadioButton.setVisible(false);
        WindowsFilesRadioButton.setVisible(false);
    }
}//GEN-LAST:event_ExcludeSystemFilesCheckBoxActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    AddingEmailSourceDialog dialogue = new AddingEmailSourceDialog(parentFrame, true);
    dialogue.setLocationRelativeTo(this);
    dialogue.setVisible(true);

    if (!dialogue.getUserName().isEmpty() || !dialogue.getPassword().isEmpty() || !dialogue.getPassword().isEmpty()) {

        if (!dialogue.cancelClicked) {
            Object[] arr = {dialogue.getUserName(), dialogue.getPassword(), dialogue.getProvider().name()};
            JTableUtil.addRowToJTable(EmailTable, arr);
        }
    }
   
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    int row = EmailTable.getSelectedRow();
    if (row < 0) {
        return;
    }
    DefaultTableModel model = (DefaultTableModel) EmailTable.getModel();
    int numRows = EmailTable.getSelectedRows().length;
    for (int i = 0; i < numRows; i++) {
        model.removeRow(EmailTable.getSelectedRow());
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
// TODO add your handling code here:
    
    String Path = (String)sourcesJList.getSelectedValue();
    JListUtil.removeFromList(Path, sourcesListModel, sourcesJList);
    
}//GEN-LAST:event_removeButtonActionPerformed

private void sourcesJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_sourcesJListValueChanged
// TODO add your handling code here:
}//GEN-LAST:event_sourcesJListValueChanged

private void addDriverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDriverButtonActionPerformed
// TODO add your handling code here:


    JDirectoryDialog directoryDialog = new JDirectoryDialog();
    directoryDialog.show(CaseWizardDialog.this);
    String path = directoryDialog.getSelectedDirectory();
    if (path == null) {
        return;
    }
    JListUtil.addToList(path, sourcesListModel, sourcesJList);
    //CaseSources = path;
}//GEN-LAST:event_addDriverButtonActionPerformed

private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JDirectoryDialog directoryDialog = new JDirectoryDialog();
        directoryDialog.show(CaseWizardDialog.this);
        String path = directoryDialog.getSelectedDirectory();

        if (path != null) {
            PATH = path;

            if (caseNameTextField.getText().trim().isEmpty()) {
                caseLocationTextField.setText(path);
            } else {
                caseLocationTextField.setText(path + "\\" + caseNameTextField.getText().trim());
            }
        }
}//GEN-LAST:event_browseButtonActionPerformed

private void YesMD5RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesMD5RadioButtonActionPerformed
// TODO add your handling code here:
     if (YesMD5RadioButton.isSelected()) {
        DetectClusterCaseRadioButton.setEnabled(true);
        DetectClusterLibraryRadioButton.setEnabled(true);
    }
}//GEN-LAST:event_YesMD5RadioButtonActionPerformed

private void NoMD5RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoMD5RadioButtonActionPerformed
// TODO add your handling code here:
    if (NoMD5RadioButton.isSelected()) {
        DetectClusterCaseRadioButton.setEnabled(false);
        DetectClusterLibraryRadioButton.setEnabled(false);
    }
    
     
}//GEN-LAST:event_NoMD5RadioButtonActionPerformed

private void DetectClusterLibraryRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetectClusterLibraryRadioButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_DetectClusterLibraryRadioButtonActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    //Handle open button action.
    final JFileChooser fc = new JFileChooser();
    File file = null;
    int returnVal = fc.showOpenDialog(this);

    if (returnVal == JFileChooser.APPROVE_OPTION) {
        file = fc.getSelectedFile();
        Runtime rt = Runtime.getRuntime();
        String output = "tools\\mount_ewf.exe" + " " + file.getPath();
        Pattern pattern = Pattern.compile("\\s");
        Matcher matcher = pattern.matcher(file.getName());
        boolean found = matcher.find();
        if (found) {
            JOptionPane.showMessageDialog(this, "Please Remove White Spaces from case file name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Process pr = rt.exec(output);
            BufferedReader input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
            String line = null;
            if(input.readLine() == null){
            JOptionPane.showMessageDialog(this, "Error Unmounting the Case", "Error", JOptionPane.ERROR_MESSAGE);    
            return;
            }
            
            int i = 0;
            while ((line = input.readLine()) != null) {
                i++;
                if (i > 0) {
                    break;
                }
                System.out.println(line);
            }   
            String[] splitedLine = line.split("\\:");
            String Path = splitedLine[1]+":\\";
            JListUtil.addToList(Path.trim(), sourcesListModel, sourcesJList);
           

        } catch (IOException ex) {
            Logger.getLogger(CaseWizardDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     else {
    }

}//GEN-LAST:event_jButton3ActionPerformed

    public boolean checkDirectIndex() {
        return indexTheCase;
    }
   
    /*
     * Check The IndexPanelInfo Before Go to the Next Panel
     * Check caseName if empty or is its existed
     * @return true if the all information are correct
     */
    private boolean checkWizardFirstPanel() throws FileNotFoundException, IOException, ClassNotFoundException {
        String caseName = getCaseName(caseNameTextField.getText().trim());
        String caseLocation = caseLocationTextField.getText().trim();
        String caseDesc = descriptionTextArea.getText();
        if (caseName == null || caseName.isEmpty()) {
            showErrorMessage("You must choose a Case Name", "Empty Index Name");
            return false;
        }
        if (caseDesc == null || caseDesc.isEmpty()) {
            showErrorMessage("You must choose Description for Case ", "Empty Description ");
            return false;
        }

        if (caseLocation == null || caseLocation.isEmpty()) {
            showErrorMessage("You must choose a Location for the Case ", "Empty Case Location");
            return false;
        }
        if (ApplicationManager.Manager.caseExists(caseName)) {
            showErrorMessage("The Case Name is Already Taken, Choose Another Name", "Case Name Exists");
            return false;
        }

        if (caseName.contains("-")) { // doesn't needed now, case name checker will remove this character!
            showErrorMessage("Case Name Should Not Contains Illegal Chatacters (-)", "Please Change Case Name And Remove Any Special Character");
            return false;
        }

        String investigator = investigatorTextField.getText().trim();
        if (investigator.isEmpty()) {
            showErrorMessage("Investigator name is empty", "Please Write A Clear Investigator Name");
            return false;
        }

        return (true);
    }

    private boolean checkWizardSecondPanel() {
     
       JListUtil.AddFromModelToList(sourcesListModel, evidencePathLocations);
        if (evidencePathLocations.isEmpty()) {
            showErrorMessage("You must choose a Case Source", "Empty Source");
            return false;
        }
        return (true);
    }

    /**
     * Check if their is folder name in case location text field
     */
    private String getCaseName(String path) {
        File file = new File(path);
        String name = file.getName();

        if (name.equalsIgnoreCase("CASES")) {
            return null;
        }

        return name;
    }

    /**
     * Move Current Panel in Card Layout to the Next Panel
     */
    private void next() {
        currentIndex++;
        GuiUtil.showPanel(cardsName[currentIndex], indexWizardPanel);
        backButton.setEnabled(true);
        nextButton.setEnabled(true);
    }

    /**
     * Move this Panel to the Next Last Panel In the Card Layout
     * Enable This Finish Button
     */
    private void nextLast() {
        currentIndex++;
        GuiUtil.showPanel(cardsName[currentIndex], indexWizardPanel);
        backButton.setEnabled(true);
        nextButton.setEnabled(false);
        finishButton.setEnabled(true);
    }

    /**
     * Return to Previous Panel in The Card Layout
     */
    private void backFirst() {
        currentIndex--;
        GuiUtil.showPanel(cardsName[currentIndex], indexWizardPanel);
        backButton.setEnabled(false);
        nextButton.setEnabled(true);
    }

    /**
     * Return to The First Panel in the Card Layout
     * Disable Finish Button
     */
    private void back() {
        currentIndex--;
        GuiUtil.showPanel(cardsName[currentIndex], indexWizardPanel);
        backButton.setEnabled(true);
        nextButton.setEnabled(true);
        finishButton.setEnabled(false);
    }


    private void showEmptyMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Object Not Found", JOptionPane.ERROR_MESSAGE);
    }

    private void showErrorMessage(String msg, String title) {       
        JOptionPane.showMessageDialog(CaseWizardDialog.this, msg, title, JOptionPane.ERROR_MESSAGE);
    }
    
    public CaseFacade getCaseFacade() { return this.caseFacade; }

    /*
     * Case Name Checker
     * Check the Validity of The Case That Created By The User
     */
    private static class CaseNameChecker {
        private static boolean isInvalidText(String text) {
            for (String word : illegalCharacters) {
                if (text.contains(word)) {
                    return true;
                }
            }

            for (String word : reservedNames) {
                if (text.equalsIgnoreCase(word)) {
                    return true;
                }
            }

            return false;
        }

        private static String removeInvalid(String text) {
            for (String s : reservedNames) {
                if (text.equalsIgnoreCase(s)) {
                    text = "";
                    return text;
                }
            }

            StringBuilder result = new StringBuilder("");

            for (int i = 0; i < text.length(); i++) {
                String ch = text.charAt(i) + "";
                if (!isInvalidText(ch)) {
                    result.append(ch);
                }
            }

            return result.toString();
        }
        /*
         * Illegal case strings and characters
         */
        private static final String[] illegalCharacters = {"<", ">", ":", "\"", "/", "\\", "|", "?", "*", "-"};
        private static final String[] reservedNames = {
            "CON", "PRN", "AUX", "NUL", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7",
            "COM8", "COM9", "LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9"
        };
    }
    
    private class PasswordCellRenderer extends JPasswordField
        implements TableCellRenderer {

        public PasswordCellRenderer() {
            super();
            this.setText("test code");
        }

        public Component getTableCellRendererComponent(JTable table, Object value, 
                boolean isSelected, boolean hasFocus, int row, int column) {
            return this;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CacheImageCheckBox;
    private javax.swing.JPanel CaseWizardA1;
    private javax.swing.JPanel CaseWizardA2;
    private javax.swing.JPanel CaseWizardA3;
    private javax.swing.ButtonGroup DataSourceButtonGroup;
    private javax.swing.JCheckBox DetectBrowserCheckBox;
    private javax.swing.JCheckBox DetectClusterCaseRadioButton;
    private javax.swing.JCheckBox DetectClusterLibraryRadioButton;
    private javax.swing.JTable EmailTable;
    private javax.swing.JCheckBox ExcludeSystemFilesCheckBox;
    private javax.swing.JCheckBox IndexChatCheckBox;
    private javax.swing.JCheckBox IndexEmbeddedFilesCheckBox;
    private javax.swing.JCheckBox IndexZipCheckBox;
    private javax.swing.JRadioButton NoIndexRadioButton;
    private javax.swing.JRadioButton NoMD5RadioButton;
    private javax.swing.JRadioButton ProgramFilesRadioButton;
    private javax.swing.JRadioButton WindowsFilesRadioButton;
    private javax.swing.JRadioButton YesIndexRadioButton;
    private javax.swing.JRadioButton YesMD5RadioButton;
    private javax.swing.ButtonGroup YesNoIndexButtonGroup;
    private javax.swing.ButtonGroup YesNoMD5HashButtonGroup;
    private javax.swing.JButton addDriverButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField caseLocationTextField;
    private javax.swing.JTextField caseNameTextField;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton finishButton;
    private javax.swing.JPanel indexFooterPanel;
    private javax.swing.JPanel indexInfoPanel;
    private javax.swing.JPanel indexWizardPanel;
    private javax.swing.JTextField investigatorTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JList sourcesJList;
    // End of variables declaration//GEN-END:variables
}
