/* 
 * Copyright (C) 2014 Center of Excellence in Information Assurance
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package edu.coeia.viewer;

import edu.coeia.items.EmailItem;
import edu.coeia.items.Item;
import edu.coeia.util.Utilities;

import java.awt.BorderLayout;

import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;

/**
 *
 * @author wajdyessam
 */
public class EmailSourceViewerPanel extends javax.swing.JPanel {

    private final String keyword ;
    private final SourceViewerDialog dialog ;
    private final JWebBrowser emailContentBrowser;
    private final Item item;
    
    /** Creates new form EmailSourceViewerPanel */
    public EmailSourceViewerPanel(SourceViewerDialog dialog, final Item item) {
        initComponents();
        
        this.dialog = dialog;
        this.keyword = dialog.getQueryString();
        this.item = item;
        
        // add file browser
        this.emailContentBrowser = new JWebBrowser();
        this.emailContentBrowser.setBarsVisible(false);
        this.emailContentBrowser.setStatusBarVisible(false);
        this.messagePanel.add(emailContentBrowser, BorderLayout.CENTER); 
        
        this.displayDocumentInformation();
    }

    private void displayDocumentInformation () {
        EmailItem emailItem = (EmailItem) this.item;
        
        String emailAgent = emailItem.getEmailSource();
        String emailSource = emailItem.getFolder();
        String emailDate = emailItem.getTime();
        String emailMessage = emailItem.getHTMLContent();
        String emailSubject = emailItem.getSubject();
        String emailTo = emailItem.getTo();
        String emailFrom = emailItem.getFrom();
        String emailCC = emailItem.getCC();
        String emailBCC = emailItem.getBCC();
        String messageHeader = emailItem.getHeader();
        
        if ( emailMessage.trim().isEmpty() ) 
            emailMessage = emailItem.getPlainContent();
        
        this.emailAgentTextField.setText(emailAgent);
        this.emailSourceTextField.setText(emailSource);
        this.messageDateTextFeild.setText(emailDate);
        this.messageTextField.setText(emailSubject);
        this.emailToTextField.setText(emailTo);
        this.emailFromTextField.setText(emailFrom);
        this.ccTextField.setText(emailCC);
        this.bccTextField.setText(emailBCC);
        
        String filteredMessage = "";
        if ( this.keyword.isEmpty() )
            filteredMessage = emailMessage.trim();
        else
            filteredMessage = Utilities.highlightString(emailMessage.trim(), this.keyword);
        
        emailContentBrowser.setHTMLContent(filteredMessage);
        
        messagePanel.validate();
        
        this.emailHeaderTextArea.setText(messageHeader);
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        messagePanel = new javax.swing.JPanel();
        emailHeaderJPanel = new javax.swing.JPanel();
        jScrollPane28 = new javax.swing.JScrollPane();
        emailHeaderTextArea = new javax.swing.JTextArea();
        properitiesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailAgentTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emailSourceTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        messageDateTextFeild = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailFromTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailToTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ccTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bccTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        messagePanel.setLayout(new java.awt.BorderLayout());
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("edu/coeia/viewer/Bundle"); // NOI18N
        jTabbedPane2.addTab(bundle.getString("EmailSourceViewerPanel.messagePanel.TabConstraints.tabTitle"), messagePanel); // NOI18N

        emailHeaderTextArea.setColumns(20);
        emailHeaderTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailHeaderTextArea.setRows(5);
        jScrollPane28.setViewportView(emailHeaderTextArea);

        javax.swing.GroupLayout emailHeaderJPanelLayout = new javax.swing.GroupLayout(emailHeaderJPanel);
        emailHeaderJPanel.setLayout(emailHeaderJPanelLayout);
        emailHeaderJPanelLayout.setHorizontalGroup(
            emailHeaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane28, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );
        emailHeaderJPanelLayout.setVerticalGroup(
            emailHeaderJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane28, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab(bundle.getString("EmailSourceViewerPanel.emailHeaderJPanel.TabConstraints.tabTitle"), emailHeaderJPanel); // NOI18N

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        add(viewPanel, java.awt.BorderLayout.CENTER);

        jLabel1.setText(bundle.getString("EmailSourceViewerPanel.jLabel1.text")); // NOI18N

        emailAgentTextField.setEditable(false);
        emailAgentTextField.setText(bundle.getString("EmailSourceViewerPanel.emailAgentTextField.text")); // NOI18N

        jLabel2.setText(bundle.getString("EmailSourceViewerPanel.jLabel2.text")); // NOI18N

        emailSourceTextField.setEditable(false);
        emailSourceTextField.setText(bundle.getString("EmailSourceViewerPanel.emailSourceTextField.text")); // NOI18N

        jLabel3.setText(bundle.getString("EmailSourceViewerPanel.jLabel3.text")); // NOI18N

        messageDateTextFeild.setEditable(false);
        messageDateTextFeild.setText(bundle.getString("EmailSourceViewerPanel.messageDateTextFeild.text")); // NOI18N

        jLabel4.setText(bundle.getString("EmailSourceViewerPanel.jLabel4.text")); // NOI18N

        messageTextField.setEditable(false);
        messageTextField.setText(bundle.getString("EmailSourceViewerPanel.messageTextField.text")); // NOI18N

        jLabel5.setText(bundle.getString("EmailSourceViewerPanel.jLabel5.text")); // NOI18N

        emailFromTextField.setEditable(false);
        emailFromTextField.setText(bundle.getString("EmailSourceViewerPanel.emailFromTextField.text")); // NOI18N

        jLabel6.setText(bundle.getString("EmailSourceViewerPanel.jLabel6.text")); // NOI18N

        emailToTextField.setEditable(false);
        emailToTextField.setText(bundle.getString("EmailSourceViewerPanel.emailToTextField.text")); // NOI18N

        jLabel7.setText(bundle.getString("EmailSourceViewerPanel.jLabel7.text")); // NOI18N

        ccTextField.setEditable(false);
        ccTextField.setText(bundle.getString("EmailSourceViewerPanel.ccTextField.text")); // NOI18N

        jLabel8.setText(bundle.getString("EmailSourceViewerPanel.jLabel8.text")); // NOI18N

        bccTextField.setEditable(false);
        bccTextField.setText(bundle.getString("EmailSourceViewerPanel.bccTextField.text")); // NOI18N

        javax.swing.GroupLayout properitiesPanelLayout = new javax.swing.GroupLayout(properitiesPanel);
        properitiesPanel.setLayout(properitiesPanelLayout);
        properitiesPanelLayout.setHorizontalGroup(
            properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(properitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(messageDateTextFeild, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(emailSourceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(emailAgentTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(emailFromTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(emailToTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(ccTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addComponent(bccTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
                .addContainerGap())
        );
        properitiesPanelLayout.setVerticalGroup(
            properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(properitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emailAgentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emailSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(messageDateTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailFromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(emailToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ccTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(bccTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(properitiesPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bccTextField;
    private javax.swing.JTextField ccTextField;
    private javax.swing.JTextField emailAgentTextField;
    private javax.swing.JTextField emailFromTextField;
    private javax.swing.JPanel emailHeaderJPanel;
    private javax.swing.JTextArea emailHeaderTextArea;
    private javax.swing.JTextField emailSourceTextField;
    private javax.swing.JTextField emailToTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField messageDateTextFeild;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JPanel properitiesPanel;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
