/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileSourceViewerPanel.java
 *
 * Created on Nov 28, 2011, 1:48:01 PM
 */
package edu.coeia.viewer;

import edu.coeia.util.Utilities;
import edu.coeia.searching.LuceneSearcher;
import edu.coeia.items.FileItem;
import edu.coeia.items.ItemFactory;
import edu.coeia.indexing.IndexingConstant;

import java.awt.BorderLayout;

import java.util.List ;

import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;

import org.apache.lucene.document.Fieldable;

/**
 *
 * @author wajdyessam
 */
class FileSourceViewerPanel extends javax.swing.JPanel {

    private final JWebBrowser fileBrowser;
    private final FileItem item;
    private final String keyword ;
    private final SourceViewerDialog searchViewerDialog ;
    private final LuceneSearcher searcher ;
    private final String currentId ;
    
    /** Creates new form FileSourceViewerPanel */
    public FileSourceViewerPanel(SourceViewerDialog dialog) {
        this.initComponents();
        
        this.searchViewerDialog = dialog;
        this.keyword = dialog.getQueryString();
        this.searcher = dialog.getLuceneSearch();
        this.currentId = dialog.getCurrentId() ;
        this.item = (FileItem) ItemFactory.newInstance(
                this.searcher.getLuceneDocumentById(String.valueOf(this.currentId)),
                this.searchViewerDialog.getCase());
                
        // add file browser
        this.fileBrowser = new JWebBrowser();
        this.fileBrowser.setBarsVisible(false);
        this.fileBrowser.setStatusBarVisible(false);
        this.fileRenderPanel.add(fileBrowser, BorderLayout.CENTER); 
        
        this.displayDocumentInformation();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        fileRenderPanel = new javax.swing.JPanel();
        textViewerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        planTextArea = new javax.swing.JTextArea();
        FileMetaDataPanel = new javax.swing.JPanel();
        jScrollPane28 = new javax.swing.JScrollPane();
        metaDataTextArea = new javax.swing.JTextArea();
        properitiesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        filePathTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mimeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        embeddedTextField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        fileRenderPanel.setLayout(new java.awt.BorderLayout());
        jTabbedPane2.addTab("HTML Viewer", fileRenderPanel);

        textViewerPanel.setLayout(new java.awt.BorderLayout());

        planTextArea.setColumns(20);
        planTextArea.setEditable(false);
        planTextArea.setFont(new java.awt.Font("Times New Roman", 0, 14));
        planTextArea.setRows(5);
        jScrollPane1.setViewportView(planTextArea);

        textViewerPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Plan Text Viewer", textViewerPanel);

        FileMetaDataPanel.setLayout(new java.awt.BorderLayout());

        metaDataTextArea.setColumns(20);
        metaDataTextArea.setEditable(false);
        metaDataTextArea.setFont(new java.awt.Font("Times New Roman", 0, 14));
        metaDataTextArea.setRows(5);
        jScrollPane28.setViewportView(metaDataTextArea);

        FileMetaDataPanel.add(jScrollPane28, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("MetaData", FileMetaDataPanel);

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                .addContainerGap())
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(viewPanel, java.awt.BorderLayout.CENTER);

        jLabel1.setText("File Name:");

        fileNameTextField.setEditable(false);
        fileNameTextField.setText(" ");

        jLabel2.setText("File Path:");

        filePathTextField.setEditable(false);
        filePathTextField.setText(" ");

        jLabel3.setText("Last Modification:");

        dateTextField.setEditable(false);
        dateTextField.setText(" ");

        jLabel4.setText("File Type:");

        mimeTextField.setEditable(false);
        mimeTextField.setText(" ");

        jLabel5.setText("Have Embedded:");

        embeddedTextField.setEditable(false);
        embeddedTextField.setText(" ");

        javax.swing.GroupLayout properitiesPanelLayout = new javax.swing.GroupLayout(properitiesPanel);
        properitiesPanel.setLayout(properitiesPanelLayout);
        properitiesPanelLayout.setHorizontalGroup(
            properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(properitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mimeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(embeddedTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(dateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(filePathTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(fileNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                .addContainerGap())
        );
        properitiesPanelLayout.setVerticalGroup(
            properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(properitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(filePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(properitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(embeddedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(properitiesPanel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents
        
    private void displayDocumentInformation () {        
        try {
            // show file properities
            String fileName = this.item.getFileName();
            String filePath = this.item.getFilePath();
            String date = this.item.getFileDate();
            String embedded = "";
            String mime = this.item.getFileMimeType();
            
            fileNameTextField.setText(fileName);
            filePathTextField.setText(filePath);
            dateTextField.setText(date);
            embeddedTextField.setText(embedded);
            mimeTextField.setText(mime);
            
            // Show File Content
            String content = this.item.getFileContent();
            fileBrowser.setHTMLContent(Utilities.highlightString(content, this.keyword));
            planTextArea.setText(content);
            
            // show matadata information for File
            List<Fieldable> fields = this.searcher.getLuceneDocumentById(String.valueOf(this.currentId)).getFields();
            StringBuilder metadataBuilder = new StringBuilder();
            
            for (Fieldable field: fields) {
                if ( !field.name().startsWith("file_") &&
                     !field.name().equalsIgnoreCase(IndexingConstant.FILE_CONTENT)) // files in IndexingConstant start with prefix file_
                    
                    metadataBuilder.append(field.name()).append(" : " ).append(field.stringValue()).append("\n");
            }
            
            String metadata = metadataBuilder.toString();
            //TODO: replace metadate view to browser or html type to support html rendering
            //metaDataTextArea.setText(highlightString(metadata, keyword));
            this.metaDataTextArea.setText(metadata);

            this.fileRenderPanel.validate();
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FileMetaDataPanel;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField embeddedTextField;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JTextField filePathTextField;
    private javax.swing.JPanel fileRenderPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea metaDataTextArea;
    private javax.swing.JTextField mimeTextField;
    private javax.swing.JTextArea planTextArea;
    private javax.swing.JPanel properitiesPanel;
    private javax.swing.JPanel textViewerPanel;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
