/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MultimediaViewerPanel.java
 *
 * Created on Jan 23, 2012, 9:27:58 AM
 */
package edu.coeia.multimedia;

import edu.coeia.cases.CaseFacade;
import edu.coeia.gutil.JTableUtil;
import edu.coeia.task.MultimediaLoadingTask;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author wajdyessam
 */
public class MultimediaViewerPanel extends javax.swing.JPanel {

    public enum TYPE { IMAGE, AUDIO, ARCHIVE, VIDEO };
    
    private final CaseFacade caseManager;
    private final TYPE type;
    
    /** Creates new form MultimediaViewerPanel */
    public MultimediaViewerPanel(final CaseFacade caseManager, final TYPE type) {
        this.initComponents();
        this.caseManager = caseManager;
        this.type = type;
        
        this.filterTableTextField.getDocument().addDocumentListener(
                new DocumentListener() { 
            public void changedUpdate(DocumentEvent e){ doFilter(); }
            public void removeUpdate (DocumentEvent e){ doFilter(); }
            public void insertUpdate (DocumentEvent e){ doFilter(); }
            
            private void doFilter() {
                JTableUtil.filterTable(itemTable,
                        filterTableTextField.getText().trim());
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        filterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filterTableTextField = new javax.swing.JTextField();
        loadItemsButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File Path", "File Extension", "Last Modification Date", "Is Hidden", "File Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTable.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(itemTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        filterPanel.setLayout(new javax.swing.BoxLayout(filterPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Filter Table:");
        filterPanel.add(jLabel1);

        filterTableTextField.setText(" ");
        filterPanel.add(filterTableTextField);

        loadItemsButton.setText("Load Items");
        loadItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadItemsButtonActionPerformed(evt);
            }
        });
        filterPanel.add(loadItemsButton);

        add(filterPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void loadItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadItemsButtonActionPerformed
        try {
            MultimediaLoadingTask task = new MultimediaLoadingTask(this.caseManager, this, type);
            task.startTask();
        } catch (Exception ex) {
            Logger.getLogger(MultimediaViewerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadItemsButtonActionPerformed

    public TYPE getType() { return this.type; }
    public JTable getTable() { return this.itemTable; }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel filterPanel;
    private javax.swing.JTextField filterTableTextField;
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadItemsButton;
    // End of variables declaration//GEN-END:variables
}
