
package edu.coeia.gui;

import edu.coeia.gui.component.GUIComponent ;


import edu.coeia.internet.IEHandler;
import edu.coeia.internet.MozillaHandler;

import edu.coeia.utility.Utilities;
import edu.coeia.utility.FilesPath ;
import edu.coeia.utility.FilesFilter ;
import edu.coeia.utility.Tuple ;

import edu.coeia.utility.MetaDataExtraction ;
import edu.coeia.utility.FireFoxHTMLReportGenerator;


import edu.coeia.cases.Case;

import edu.coeia.chat.MSNParser;
import edu.coeia.chat.YahooMessage ;
import edu.coeia.chat.YahooMessageDecoder;
import edu.coeia.chat.YahooMessageReader;
import edu.coeia.chat.SkypeMessage;
import edu.coeia.chat.SkypeParser;

import edu.coeia.search.PSTSearcher;
import edu.coeia.internet.InternetSummaryDate ;


import edu.coeia.email.EmailReaderThread;
import edu.coeia.email.MessageHeader ;

import java.awt.CardLayout ;
import java.awt.BorderLayout;

import java.awt.Toolkit ;

import java.awt.Desktop ;
import java.awt.event.InputEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JButton;
import javax.swing.JPopupMenu;
import javax.swing.border.TitledBorder;
import javax.swing.JFileChooser ;
import javax.swing.JTextField ;
import javax.swing.JComboBox ;
import javax.swing.JOptionPane ;
import javax.swing.JTable ;
import javax.swing.RowFilter ;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter ;
import javax.swing.table.TableModel ;
import javax.swing.tree.DefaultMutableTreeNode ;
import javax.swing.tree.DefaultTreeModel ;
import javax.swing.ListSelectionModel ;
import javax.swing.event.ListSelectionListener ;
import javax.swing.event.ListSelectionEvent ;
import javax.swing.event.TreeSelectionListener ;
import javax.swing.event.TreeSelectionEvent ;
import javax.swing.JPanel ;
import javax.swing.JFrame ;
import javax.swing.event.DocumentEvent ;
import javax.swing.event.DocumentListener ;
import javax.swing.JLabel;


import java.io.File ;
import java.io.FileNotFoundException ;
import java.io.IOException ;
import java.io.FilenameFilter ;

import java.util.List; 
import java.util.ArrayList ;
import java.util.HashMap ;
import java.util.Vector ;
import java.util.Iterator ;
import java.util.Map ;
import java.util.Set ;
import java.util.Date ;
import java.util.regex.PatternSyntaxException;

import java.sql.SQLException ;

import java.net.URISyntaxException ;
import java.net.URI ;

import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;

import java.util.logging.Logger;
import java.util.logging.Level;

/*
 * ChatPanel.java
 *
 * @author wajdyessam
 * 
 * Created on Aug 10, 2011, 4:20:30 PM
 * 
 */

public class ChatPanel extends javax.swing.JPanel {

    // msn chat
    private DefaultMutableTreeNode rootMSNNode ;
    private MSNParser msnParser ;
    private JWebBrowser msnChat = new JWebBrowser();

    // yaho chat
    private DefaultMutableTreeNode rootYahooNode;
    private JWebBrowser yahooChat = new JWebBrowser();

    // skype Chat
    private DefaultMutableTreeNode rootSkypeNode ;
    
    private Logger logger = Logger.getLogger(this.getClass().getName());
    private Case index;
    private JFileChooser fileChooser ;
    
    /** Creates new form ChatPanel */
    public ChatPanel() {
        initComponents();
        
        // configure file chooser to select files (txt)
        fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new FilesFilter("Text Files (*.txt)", "txt"));
        
        // set msn & yahoo & skype data to thier combobox
        for (String yahooPath: index.getYahooPath())
            yahooComboBox.addItem(yahooPath);

        for (String msnPath: index.getMsnPath())
            msnComboBox.addItem(msnPath);

        for (String skypePath: index.getSkypePath())
            skypeComboBox.addItem(skypePath);
        
        // yahoo chat display area
        yahooChatContentPanel.add(yahooChat, BorderLayout.CENTER);
        yahooChat.setBarsVisible(false);
        yahooChat.setStatusBarVisible(false);

        // msn chat display area
        msnChat.setBarsVisible(false);
        msnChat.setStatusBarVisible(false);
        msnChatContentPanel.add(msnChat, BorderLayout.CENTER);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatPanelTappedPane = new javax.swing.JTabbedPane();
        WindowsLivePanel = new javax.swing.JPanel();
        msnChatContentPanel = new javax.swing.JPanel();
        jScrollPane20 = new javax.swing.JScrollPane();
        msnChatTree = new javax.swing.JTree();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        msnComboBox = new javax.swing.JComboBox();
        loadMSNButton = new javax.swing.JButton();
        yahooMessangerPanel = new javax.swing.JPanel();
        jScrollPane21 = new javax.swing.JScrollPane();
        yahooChatTree = new javax.swing.JTree();
        yahooChatContentPanel = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        yahooComboBox = new javax.swing.JComboBox();
        loadYahooButton = new javax.swing.JButton();
        skypePanel = new javax.swing.JPanel();
        skypeChatContentPanel = new javax.swing.JPanel();
        jScrollPane18 = new javax.swing.JScrollPane();
        skypeTable = new javax.swing.JTable();
        jScrollPane23 = new javax.swing.JScrollPane();
        skypeChatTree = new javax.swing.JTree();
        jPanel20 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        skypeComboBox = new javax.swing.JComboBox();
        loadSkypeButton = new javax.swing.JButton();

        msnChatContentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        msnChatContentPanel.setLayout(new java.awt.BorderLayout());

        msnChatTree.setModel(null);
        msnChatTree.setShowsRootHandles(true);
        msnChatTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                msnChatTreeValueChanged(evt);
            }
        });
        jScrollPane20.setViewportView(msnChatTree);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setForeground(new java.awt.Color(0, 70, 213));
        jLabel7.setText("Select Window Live File From Index:");

        loadMSNButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        loadMSNButton.setText("Load Conversations");
        loadMSNButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMSNButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(msnComboBox, 0, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(loadMSNButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(msnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadMSNButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout WindowsLivePanelLayout = new javax.swing.GroupLayout(WindowsLivePanel);
        WindowsLivePanel.setLayout(WindowsLivePanelLayout);
        WindowsLivePanelLayout.setHorizontalGroup(
            WindowsLivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WindowsLivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WindowsLivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WindowsLivePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(msnChatContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        WindowsLivePanelLayout.setVerticalGroup(
            WindowsLivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WindowsLivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WindowsLivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(msnChatContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addContainerGap())
        );

        chatPanelTappedPane.addTab("Windows Live Messanger", WindowsLivePanel);

        yahooChatTree.setModel(null);
        yahooChatTree.setShowsRootHandles(true);
        yahooChatTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                yahooChatTreeValueChanged(evt);
            }
        });
        jScrollPane21.setViewportView(yahooChatTree);

        yahooChatContentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        yahooChatContentPanel.setLayout(new java.awt.BorderLayout());

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setForeground(new java.awt.Color(0, 70, 213));
        jLabel9.setText("Select Yahoo File From Index:");

        loadYahooButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        loadYahooButton.setText("Load Conversations");
        loadYahooButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadYahooButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(yahooComboBox, 0, 234, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(loadYahooButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(yahooComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadYahooButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout yahooMessangerPanelLayout = new javax.swing.GroupLayout(yahooMessangerPanel);
        yahooMessangerPanel.setLayout(yahooMessangerPanelLayout);
        yahooMessangerPanelLayout.setHorizontalGroup(
            yahooMessangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yahooMessangerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(yahooMessangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(yahooMessangerPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yahooChatContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)))
                .addContainerGap())
        );
        yahooMessangerPanelLayout.setVerticalGroup(
            yahooMessangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yahooMessangerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(yahooMessangerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yahooChatContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addContainerGap())
        );

        chatPanelTappedPane.addTab("Yahoo Messanger", yahooMessangerPanel);

        skypeChatContentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        skypeTable.setFont(new java.awt.Font("Tahoma", 1, 11));
        skypeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Auther","Partner","Time","Message"
            }
        ));
        skypeTable.setGridColor(new java.awt.Color(255, 255, 255));
        skypeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                skypeTableMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                skypeTableMouseReleased(evt);
            }
        });
        jScrollPane18.setViewportView(skypeTable);

        skypeChatTree.setModel(null);
        skypeChatTree.setShowsRootHandles(true);
        skypeChatTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                skypeChatTreeValueChanged(evt);
            }
        });
        jScrollPane23.setViewportView(skypeChatTree);

        javax.swing.GroupLayout skypeChatContentPanelLayout = new javax.swing.GroupLayout(skypeChatContentPanel);
        skypeChatContentPanel.setLayout(skypeChatContentPanelLayout);
        skypeChatContentPanelLayout.setHorizontalGroup(
            skypeChatContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skypeChatContentPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
        );
        skypeChatContentPanelLayout.setVerticalGroup(
            skypeChatContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
            .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel28.setForeground(new java.awt.Color(0, 70, 213));
        jLabel28.setText("Select Skypee File From Index:");

        loadSkypeButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        loadSkypeButton.setText("Load Conversations");
        loadSkypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSkypeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(skypeComboBox, 0, 244, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(loadSkypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(skypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadSkypeButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout skypePanelLayout = new javax.swing.GroupLayout(skypePanel);
        skypePanel.setLayout(skypePanelLayout);
        skypePanelLayout.setHorizontalGroup(
            skypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(skypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skypeChatContentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        skypePanelLayout.setVerticalGroup(
            skypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(skypeChatContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        chatPanelTappedPane.addTab("Skype Messanger", skypePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatPanelTappedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chatPanelTappedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void msnChatTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_msnChatTreeValueChanged
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) msnChatTree.getLastSelectedPathComponent();

        if ( node == null || node.isRoot() )
            return ;

        String parent = node.getParent().toString();

        if ( FilesPath.getOSType() == FilesPath.OS_TYPE.XP){
            String value = msnParser.getAllUserLoggingPath().get(parent);

            if ( value != null ) {
                File file = new File( msnParser.getFileFromPath(value,node.getUserObject().toString()));
                if ( file.exists() ) {
                    msnChat.navigate(file.getAbsolutePath());
                    msnChatContentPanel.revalidate();
                }
            }
            else {
                if ( ! node.isLeaf() )
                    msnChat.setHTMLContent("");
                else
                    msnChat.setHTMLContent("there is no history for this user");

                msnChatContentPanel.revalidate();
            }
        }
        else {
            File file = new File( msnComboBox.getSelectedItem() + "\\" + node.getUserObject().toString());
            if ( file.exists() ) {
                msnChat.navigate(file.getAbsolutePath());
                msnChatContentPanel.revalidate();
            }
        }
}//GEN-LAST:event_msnChatTreeValueChanged

private void loadMSNButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMSNButtonActionPerformed
        String path = (String) msnComboBox.getSelectedItem();

        try {
            fillMessangerTree(path);
            msnChatTree.setModel(new DefaultTreeModel(rootMSNNode));
        }
        catch (IOException e){
            logger.log(Level.SEVERE, "Uncaught exception", e);
        }
}//GEN-LAST:event_loadMSNButtonActionPerformed

private void yahooChatTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_yahooChatTreeValueChanged
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) yahooChatTree.getLastSelectedPathComponent();

        if ( node == null || node.isRoot() || ! node.isLeaf()) {
            return ;
        }

        String parent = node.getParent().toString();
        String current= node.getUserObject().toString();
        
        try {
            String path = (String) yahooComboBox.getSelectedItem() ;
            ArrayList<ArrayList<YahooMessage>> msgs  = YahooMessageReader.getInstance(path).get(parent).get(current) ;
            if ( msgs == null ) {
                return ;
            }

            StringBuilder text = new StringBuilder("");
            
            for (ArrayList<YahooMessage> aList: msgs) {
                for (YahooMessage msg: aList) {
                    if ( msg.getMessagePath() == YahooMessage.MESSAGE_PATH.SOURCE_TO_DEST ) {
                        text.append(msg.getProfileName() + " at (" );
                    }
                    else {
                        text.append(msg.getDestinationName() + " at (" );
                    }

                    text.append( Utilities.formatDateTime(msg.getTimeStamp()) + ") :  " );
                    
                    byte[] cipher = msg.getCipherText();
                    String name   = msg.getProfileName();
                    byte[] plainText  = YahooMessageDecoder.decode(cipher,name);

                    String plain = new String(plainText, "UTF-8");
                    text.append( plain );
                    text.append("<br>");
                }

                text.append("<br>");
                text.append("<br>");
            }

            yahooChat.setHTMLContent(text.toString());
            yahooChatContentPanel.revalidate();
        }
        catch (IOException e){
            logger.log(Level.SEVERE, "Uncaught exception", e);

        }
}//GEN-LAST:event_yahooChatTreeValueChanged

private void loadYahooButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadYahooButtonActionPerformed
        String path = (String) yahooComboBox.getSelectedItem();
        
        try {
            fillYahooTree(path);
            yahooChatTree.setModel(new DefaultTreeModel(rootYahooNode));
        }
        catch (IOException e){
            logger.log(Level.SEVERE, "Uncaught exception", e);
        }  
}//GEN-LAST:event_loadYahooButtonActionPerformed

private void skypeTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skypeTableMousePressed
        if ( (evt.getModifiersEx() & InputEvent.BUTTON3_DOWN_MASK ) != 0 ) {
            if ( skypeTable.isEnabled() )
                showPopup(evt);
        }
}//GEN-LAST:event_skypeTableMousePressed

private void skypeTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skypeTableMouseReleased
        if ( (evt.getModifiersEx() & InputEvent.BUTTON3_DOWN_MASK ) != 0 ) {
            if ( skypeTable.isEnabled() )
                showPopup(evt);
        }
}//GEN-LAST:event_skypeTableMouseReleased

private void skypeChatTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_skypeChatTreeValueChanged
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) skypeChatTree.getLastSelectedPathComponent();

        if ( node == null || node.isRoot() || ! node.isLeaf()) {
            return ;
        }

        String current= node.getUserObject().toString();

        try {
            String path = (String) skypeComboBox.getSelectedItem() ;
            SkypeParser parser = new SkypeParser();
            ArrayList<Tuple<String, ArrayList<SkypeMessage>>> msgs = parser.parseSkypeFile(path);

            for (Tuple<String, ArrayList<SkypeMessage>> user: msgs) {
                if ( user.getA().equals(current)) {
                    DefaultTableModel model = (DefaultTableModel) skypeTable.getModel();
                    for (SkypeMessage msg: user.getB()) {
                        model.addRow(new Object[] {
                            msg.getAuther(),msg.getPartner(), msg.getDate(), msg.getMessageText()
                        });
                    }
                    return ;
                }
            }
        }
        catch (Exception e){
            logger.log(Level.SEVERE, "Uncaught exception", e);
        }
}//GEN-LAST:event_skypeChatTreeValueChanged

private void loadSkypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSkypeButtonActionPerformed
        String path = (String) skypeComboBox.getSelectedItem();
        
        try {
            if ( skypeTable.getModel().getRowCount() > 0 )
                 Utilities.removeAllRows(skypeTable);
            
            fillSkypeTree(path);
            skypeChatTree.setModel(new DefaultTreeModel(rootSkypeNode));
        }
        catch (IOException e){
            logger.log(Level.SEVERE, "Uncaught exception", e);
        }
}//GEN-LAST:event_loadSkypeButtonActionPerformed

    private void fillSkypeTree (String path) throws IOException {
        rootSkypeNode = new DefaultMutableTreeNode("Skype Chat");
        SkypeParser parser = new SkypeParser();
        
        try {
            ArrayList<Tuple<String, ArrayList<SkypeMessage>>> msgs = parser.parseSkypeFile(path);

            if ( msgs == null)
                return ;

            for (Tuple<String, ArrayList<SkypeMessage>> user: msgs) {
                DefaultMutableTreeNode node = new DefaultMutableTreeNode(user.getA());
                rootSkypeNode.add(node);
            }
        }
        catch (Exception e){
        }
    }
    
    public void fillMessangerTree (String path) throws IOException {
        rootMSNNode = new DefaultMutableTreeNode("Windows Live Messanger");

        if ( FilesPath.getOSType() == FilesPath.OS_TYPE.XP) {
            path = path.split("\\\\")[0] + "\\" + "WINDOWS\\System32\\reg.exe" ;

            msnParser = new MSNParser(path);
            msnParser.parse();

            HashMap<String,String> map = msnParser.getAllUserLoggingPath();
            ArrayList<String> list = msnParser.getAllUserLoggingToMsn();

            DefaultMutableTreeNode historyNode = new DefaultMutableTreeNode("Users Have Histories");
            DefaultMutableTreeNode normalNode  = new DefaultMutableTreeNode("Users Without Histories");

            rootMSNNode.add(historyNode);
            Set set = map.entrySet();
            Iterator itr = set.iterator();
            while ( itr.hasNext() ) {
                Map.Entry me = (Map.Entry) itr.next();

                String key = (String) me.getKey();
                String value = (String) me.getValue();

                DefaultMutableTreeNode subNode = new DefaultMutableTreeNode(key) ;
                historyNode.add(subNode);
                addOtherUserRelatedToKey(subNode,value);
            }

            rootMSNNode.add(normalNode);
            for (int i=0 ; i<list.size() ; i++)
                normalNode.add(new DefaultMutableTreeNode(list.get(i)));
        }
        else {
            DefaultMutableTreeNode historyNode = new DefaultMutableTreeNode("Users Have Histories");
            rootMSNNode.add(historyNode);

            ArrayList<String> list = getUsersName(path);
            for (String name: list) {
                DefaultMutableTreeNode subNode = new DefaultMutableTreeNode(name) ;
                historyNode.add(subNode);
            }
            
        }
    }

    private ArrayList<String> getUsersName (String path) {
        File[] files = getAllFiles(path);
        ArrayList<String> names = new ArrayList<String>();

        for(File f: files) {
            String name = f.getName();
            names.add(name);
        }

        return names;
    }

    private File[] getAllFiles (String path) {
        File dir = new File(path);

        File[] files = dir.listFiles( new FilenameFilter() {
                public boolean accept (File dir, String name) {
                    return name.toLowerCase().endsWith(".xml");
                }
            }
        );

        return (files);
    }

    private void addOtherUserRelatedToKey (DefaultMutableTreeNode node , String path) throws IOException {
        File[] files = msnParser.getAllFiles(path);

        for (File f: files) {
            DefaultMutableTreeNode tmpNode = new DefaultMutableTreeNode(msnParser.getFileName(f.getName()));
            node.add(tmpNode);
        }
    }
    
    public void fillYahooTree (String path) throws IOException {
        rootYahooNode = new DefaultMutableTreeNode("Yahoo! Chat");
        HashMap<String, HashMap<String, ArrayList<ArrayList<YahooMessage>>>> map = YahooMessageReader.getInstance(path);

        for (Map.Entry<String,HashMap<String,ArrayList<ArrayList<YahooMessage>>>> mapEntry: map.entrySet() ) {
            String currentUserName = mapEntry.getKey();
            DefaultMutableTreeNode nameNode = new DefaultMutableTreeNode(currentUserName);
            rootYahooNode.add(nameNode);


            for(Map.Entry<String,ArrayList<ArrayList<YahooMessage>>> subMapEntry: mapEntry.getValue().entrySet()) {
                String otherUserName = subMapEntry.getKey();
                DefaultMutableTreeNode subNodeName = new DefaultMutableTreeNode(otherUserName);
                nameNode.add(subNodeName);
            }
        }
    }
    
    private void showPopup (java.awt.event.MouseEvent event) {
        final JTable table = (JTable) event.getSource();
        JPopupMenu popup = new JPopupMenu();
        JButton btn = new JButton("Export to CSV File");
        
        btn.addActionListener( new java.awt.event.ActionListener() {
            public void actionPerformed (java.awt.event.ActionEvent event) {
                try {
                    FilesFilter ffFilter = new FilesFilter("Comma Seperated Value","CSV");
                    fileChooser.setFileFilter(ffFilter);

                    int result = fileChooser.showSaveDialog(null);

                    if ( result == JFileChooser.APPROVE_OPTION) {
                        String name = fileChooser.getSelectedFile().getAbsolutePath();
                        Utilities.exportJTable(table,name);
                    }
                }
                catch (Exception e){
                }
            }
        });

        popup.add(btn);
        table.setComponentPopupMenu(popup);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WindowsLivePanel;
    private javax.swing.JTabbedPane chatPanelTappedPane;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JButton loadMSNButton;
    private javax.swing.JButton loadSkypeButton;
    private javax.swing.JButton loadYahooButton;
    private javax.swing.JPanel msnChatContentPanel;
    private javax.swing.JTree msnChatTree;
    private javax.swing.JComboBox msnComboBox;
    private javax.swing.JPanel skypeChatContentPanel;
    private javax.swing.JTree skypeChatTree;
    private javax.swing.JComboBox skypeComboBox;
    private javax.swing.JPanel skypePanel;
    private javax.swing.JTable skypeTable;
    private javax.swing.JPanel yahooChatContentPanel;
    private javax.swing.JTree yahooChatTree;
    private javax.swing.JComboBox yahooComboBox;
    private javax.swing.JPanel yahooMessangerPanel;
    // End of variables declaration//GEN-END:variables
}
